name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3]
        
    name: PHP ${{ matrix.php-version }} Code Quality
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, json, zip, pdo, mysql
        coverage: xdebug
        
    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Run code style check
      run: composer cs-check
      
    - name: Run static analysis
      run: |
        if [ -f "vendor/bin/phpstan" ]; then
          vendor/bin/phpstan analyse
        else
          echo "PHPStan not installed, skipping"
        fi
      
    - name: Run tests
      run: |
        if [ -f "vendor/bin/phpunit" ]; then
          composer test
        else
          echo "PHPUnit not installed, skipping tests"
        fi

  markdown-lint:
    runs-on: ubuntu-latest
    name: Markdown Lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Lint markdown files
      uses: DavidAnson/markdownlint-cli2-action@v14
      with:
        globs: '**/*.md' 